-- EXAM.BURGER_ITEM definition



CREATE TABLE "EXAM"."BURGER_ITEM" 
   (	"ITEM_CODE" VARCHAR2(13) NOT NULL ENABLE, 
	"DIV_CODE" CHAR(3) NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(100), 
	"PRICE" NUMBER(12,0), 
	"SET_YN" VARCHAR2(1), 
	"USED_YN" VARCHAR2(1), 
	"REG_DATETIME" VARCHAR2(8), 
	"REG_CODE" VARCHAR2(12), 
	"UPD_DATETIME" VARCHAR2(8), 
	"UPD_CODE" VARCHAR2(12), 
	 CONSTRAINT "ITEM_PK" PRIMARY KEY ("ITEM_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM"  ENABLE, 
	 CONSTRAINT "FK01_BURGER_ITEM" FOREIGN KEY ("DIV_CODE")
	  REFERENCES "EXAM"."BURGER_ITEM_DIV" ("DIV_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM" ;

  
 -- EXAM.BURGER_EMP definition

CREATE TABLE "EXAM"."BURGER_EMP" 
   (	"EMP_CODE" VARCHAR2(12) NOT NULL ENABLE, 
	"STORE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"EMP_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"EMP_PW" VARCHAR2(12), 
	"UP_EMP" VARCHAR2(12), 
	"RANK" VARCHAR2(50), 
	"POSITION" VARCHAR2(50), 
	"TEL_NO" VARCHAR2(20), 
	"E_MAIL" VARCHAR2(100), 
	"EMP_ADDR" VARCHAR2(500), 
	"EMP_BIRTHDAY" VARCHAR2(8), 
	 CONSTRAINT "BURGER_EMP_PK" PRIMARY KEY ("EMP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM"  ENABLE, 
	 CONSTRAINT "FK02_BURGER_EMP" FOREIGN KEY ("UP_EMP")
	  REFERENCES "EXAM"."BURGER_EMP" ("EMP_CODE") ENABLE, 
	 CONSTRAINT "FK01_BURGER_EMP" FOREIGN KEY ("STORE_CODE")
	  REFERENCES "EXAM"."BURGER_STORE" ("STORE_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM" ;

  
  -- EXAM.BURGER_ITEM_DIV definition

CREATE TABLE "EXAM"."BURGER_ITEM_DIV" 
   (	"DIV_CODE" CHAR(3) NOT NULL ENABLE, 
	"DIV_NAME" VARCHAR2(50), 
	"USED_YN" VARCHAR2(1), 
	"REG_DATETIME" DATE, 
	"REG_CODE" VARCHAR2(20), 
	"UPD_DATETIME" DATE, 
	"UPD_CODE" VARCHAR2(12), 
	 CONSTRAINT "DIV_PK" PRIMARY KEY ("DIV_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM" ;
  
  
  -- EXAM.BURGER_ORD definition

CREATE TABLE "EXAM"."BURGER_ORD" 
   (	"STORE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"ORD_CODE" VARCHAR2(16) NOT NULL ENABLE, 
	"ORD_DATE" VARCHAR2(8), 
	"ORD_TIME" VARCHAR2(4), 
	"ORD_CNT" NUMBER(5,0), 
	"ORD_AMOUNT" NUMBER(12,0), 
	"DISCOUNT_YN" VARCHAR2(1), 
	"DISCOUNT_AMOUNT" NUMBER(12,0), 
	"PAYMENT_AMOUNT" NUMBER(12,0), 
	"CARD_PAYMENTS" NUMBER(12,0), 
	"CASH_PAYMENTS" NUMBER(12,0), 
	"CANCEL_YN" VARCHAR2(1), 
	"CANCEL_DATETIME" DATE, 
	"EMP_CODE" VARCHAR2(12), 
	 CONSTRAINT "BURGER_ORD_PK" PRIMARY KEY ("STORE_CODE", "ORD_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM"  ENABLE, 
	 CONSTRAINT "FK02_BURGER_ORD" FOREIGN KEY ("EMP_CODE")
	  REFERENCES "EXAM"."BURGER_EMP" ("EMP_CODE") ENABLE, 
	 CONSTRAINT "FK01_BURGER_ORD" FOREIGN KEY ("STORE_CODE")
	  REFERENCES "EXAM"."BURGER_STORE" ("STORE_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM" ;

  
 
  -- EXAM.BURGER_ORD_ITEM definition

GUESS WHAT the colume name of ORD_SEQ
CREATE TABLE "EXAM"."BURGER_ORD_ITEM" 
   (	"STORE_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"ORD_CODE" VARCHAR2(16) NOT NULL ENABLE, 
	"ORD_SEQ" NUMBER(5,0) NOT NULL ENABLE, 
	"SET_YN" VARCHAR2(1), 
	"QTY" NUMBER(5,0), 
	"PRICE" NUMBER(12,0), 
	"AMOUNT" NUMBER(12,0), 
	"CANCEL_YN" VARCHAR2(1), 
	"ITEM_CODE" VARCHAR2(13), 
	 CONSTRAINT "BURGER_ORD_ITEM_PK" PRIMARY KEY ("STORE_CODE", "ORD_CODE", "ORD_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 7340032 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM"  ENABLE, 
	 CONSTRAINT "FK01_BURGER_ORD_ITEM" FOREIGN KEY ("ITEM_CODE")
	  REFERENCES "EXAM"."BURGER_ITEM" ("ITEM_CODE") ENABLE, 
	 CONSTRAINT "FK02_BURGER_ORD_ITEM" FOREIGN KEY ("STORE_CODE", "ORD_CODE")
	  REFERENCES "EXAM"."BURGER_ORD" ("STORE_CODE", "ORD_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM" ;

  
  -- EXAM.BURGER_SET_ITEM definition

CREATE TABLE "EXAM"."BURGER_SET_ITEM" 
   (	"SET_ITEM_CODE" VARCHAR2(13) NOT NULL ENABLE, 
	"UNIT_ITEM_CODE" VARCHAR2(13) NOT NULL ENABLE, 
	"UNIT_ITEM_NAME" VARCHAR2(200), 
	"UNIT_QTY" NUMBER(5,0), 
	"OPTION_YN" VARCHAR2(1), 
	"OPTION_GROUP" VARCHAR2(2), 
	 CONSTRAINT "BUGER_SET_ITEM_PK" PRIMARY KEY ("SET_ITEM_CODE", "UNIT_ITEM_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM"  ENABLE, 
	 CONSTRAINT "FK01_BURGER_SET_ITEM" FOREIGN KEY ("SET_ITEM_CODE")
	  REFERENCES "EXAM"."BURGER_ITEM" ("ITEM_CODE") ENABLE, 
	 CONSTRAINT "FK02_BURGER_SET_ITEM" FOREIGN KEY ("UNIT_ITEM_CODE")
	  REFERENCES "EXAM"."BURGER_ITEM" ("ITEM_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM" ;

  
  -- EXAM.BURGER_STORE definition

CREATE TABLE "EXAM"."BURGER_STORE" 
   (	"STORE_CODE" VARCHAR2(3), 
	"STORE_ADDR" VARCHAR2(200), 
	"STORE_TEL" VARCHAR2(20), 
	"STORE_FAX" VARCHAR2(20), 
	"STORE_OPEN" VARCHAR2(8), 
	"OPEN_TIME" VARCHAR2(4), 
	"CLOSE_TIME" VARCHAR2(4), 
	"STORE_SIZE" VARCHAR2(50), 
	"TABLE_CNT" NUMBER(5,0), 
	 CONSTRAINT "PC_BURGER_STORE" PRIMARY KEY ("STORE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_EXAM" ;


  
  
   
  
  
  